import os
import sys
from io import StringIO

sourcedir = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.join(sourcedir, '../src'))

from ninju import NINJU_VERSION, NINJU_URL, NINJA_REQUIRED_VERSION

HEADER = """# This file is generated by Ninju v{}
# ({})

ninja_required_version = {}
root = .
builddir = ${{root}}/.builddir""".format(
    NINJU_VERSION,
    NINJU_URL,
    NINJA_REQUIRED_VERSION)


def generate_ninja(ninju, newline=True):
    o = StringIO()
    w = ninju._generate(o, newline)
    result = o.getvalue()
    w.close()
    return result
