import os
import sys
from io import StringIO

sourcedir = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.join(sourcedir, '../src'))

from ninju import NINJU_VERSION, NINJU_URL, NINJA_REQUIRED_VERSION
from ninju import NINJU_MODULE_PATH, NINJA_SYNTAX_MODULE_PATH

def Header(module_file):
  return """# This file is generated by Ninju v{}
# ({})

ninja_required_version = {}
root = .
builddir = ${{root}}/.builddir
rule configure
  command = {}
  description = Regenerate ninja build file
  generator = 1
build ${{root}}/build.ninja: configure | $
    {} $
    {} $
    {}""".format(
    NINJU_VERSION,
    NINJU_URL,
    NINJA_REQUIRED_VERSION,
    module_file,
    module_file,
    NINJU_MODULE_PATH,
    NINJA_SYNTAX_MODULE_PATH)


def generate_ninja(ninju, newline=True):
    o = StringIO()
    w = ninju._generate(o, newline)
    result = o.getvalue()
    w.close()
    return result
